export const CURRENT_PAGE_ADD = 'CURRENT_PAGE_ADD'
export const CHANGE_TOTAL_PAGE = 'CHANGE_TOTAL_PAGE'
export const SET_LIST_DATA = 'SET_LIST_DATA'
export const LIST_IS_LOADING = 'LIST_IS_LOADING'